version: '3'
services:
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniominio
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
volumes:
  minio_data: